### ISSUE TITLE
Setup & test a protocol to access the Double2 Robot on the Loose  in DoES for project participants

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/P3K#4]
Be good to test a system maybe using the Domestic Science google calendar to coordinate times people on the project can meet up using [Double2 Robot on the Loose](https://twitter.com/wheeliepad) Viandira really liked the idea when we met with @hwayounggit !

**Comment by hwayounggit** [comment]
Be good to test out what strength wifi is needed to keep a connection going. Could also test out with Kathleen in Surabaya for connectivity strength.

**Comment by cheapjack** [comment]
1. Host physically goes to the Wheeliepad in DoESLiverpool and removes it from it's charging dock. 
2. Click on the face icon on the pad's 'face' (bottom left) and set up a visitor pass for 24 Hours for a new visitor
3. Email it to the host's email address. (This avoids first time wheeliepad email links going to spam)
4. Host emails it to our visitors, for example @kathleenazali . 
5. Visitor clicks emailed link. Best using Google Chrome or Mozilla Firefox Browsers, which work best with the wheeliepad web interface. Hopefully internet fast enough to enable video and control of the robot around the space

![image1](https://user-images.githubusercontent.com/128456/62049709-b86a4c00-b207-11e9-90eb-d4b6ca2c9563.jpeg)
(thanks to julian for letting us use wheeliepad!)
